### ISSUE TITLE
openStripeCheckout not defined on Gatsby V2

### ISSUE THREAD

**Issue by benwis** [njosefbeck/gatsby-plugin-stripe-checkout#3] opened 2018-08-30 00:31 UTC
I've installed the module and added it to gatsby-config.js, but it looks like things are somehow loaded differently? I get the error below when I try to include a checkout component on the page, perhaps its not finding the checkout.js file, but it can be seen in the inspector on page load
```
✖ 1 problem (1 error, 0 warnings)


 @ ./src/pages/index.js 12:0-46
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/react-hot-loader/patch.js (webpack)-hot-middleware/client.js?path=http://localhost:8000/__webpack_hmr&reload=true&overlay=false G://Works//projects//Lou//gatsbyv2Frontend//.cache//app

× ｢wdm｣:
ERROR in ./src/components/checkout.js
Module Error (from ./node_modules/eslint-loader/index.js):

G:\Works\projects\Lou\gatsbyv2Frontend\src\components\checkout.js
  43:26  error  'StripeCheckout' is not defined  no-undef
```

**Comment by njosefbeck** [comment] 2018-08-30 00:42
@benwis Hello! If the checkout.js file is showing up on each page of your site, then the plugin is working as intended. Though the following project is a little outdated, and I need to work on updating it to be inline with the new version of Gatsby, maybe this file would help you: https://github.com/njosefbeck/unicorn-mart/blob/master/src/components/cart.js.

Also, if you have some code I can look at that'd make it easier for me to help you debug! Thanks.

**Comment by njosefbeck** [comment] 2018-08-30 01:21
As a follow up, I have updated my example project to use Gatsby 1.9.277 and the checkout works just fine (https://unicorn-mart.netlify.com/). I have yet to update it to Gatsby v2 since that's still in beta. 

Happy to look at some code you have to help you debug. In the meantime I'll also work on updating the project to v2 and see if I run into any issues.

**Comment by benwis** [comment] 2018-08-30 02:18
It looks like I've got it working now. The trouble is that in v2 gatsby seems to have applied a strict default eslint ruleset, which isn't allowing the undefined openStripeCheckout. I was able to override it by adding a .eslintrc file with a very basic ruleset, but it would have been nice to get some notice that Gatsby does that. Details here:  https://github.com/gatsbyjs/gatsby/issues/5493

**Comment by njosefbeck** [comment] 2018-08-30 13:30
Yeah, maybe in their v2 documentation they'll add something about that. As you seemed to have figured it out, going to close this for now. Feel free to re-open if you run into any further issues! Thanks!

**Closed as completed by njosefbeck** 2018-08-30 13:30 UTC
